# Generated by Django 3.0.8 on 2020-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taubrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='static/taubrix/imagenes/no-img.jpg', upload_to='static/taubrix/imagenes'),
        ),
    ]
